name: Regression Tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_call:
  workflow_dispatch:
# Cancel old runs when a new commit is pushed to the same branch if not on main or dev
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
defaults:
  run:
    working-directory: .
jobs:
  regression-test-callback:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - name: Trigger workflow in external repo
      run: |
        curl -X POST \
             -H "Authorization: token ${{ secrets.EXTERNAL_REPO_PAT }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/mosaicml/testing/actions/workflows/slack-callback.yaml/dispatches
             -d '{"ref":"main", "inputs": {"test_suite_passed" : false }}'
